export const GAME_CONFIG = {
  // Display
  WIDTH: 1280,
  HEIGHT: 720,

  // Level
  LEVEL_WIDTH: 9000,
  GROUND_Y: 620,
  CEILING_Y: 40,

  // Player physics
  PLAYER_SPEED: 400,
  JUMP_VELOCITY: -650,
  GRAVITY: 1200,
  AIR_CONTROL: 0.9,

  // Player dimensions
  BODY_WIDTH: 30,
  BODY_HEIGHT: 60,
  HEAD_RADIUS: 10,
  LINE_WIDTH: 3,

  // Web-slinging
  WEB_MAX_LENGTH: 350,
  WEB_MIN_LENGTH: 80,
  WEB_COOLDOWN: 80,
  WEB_RELEASE_BOOST: 1.5,
  WEB_PUMP_FORCE: 800,
  WEB_ATTACH_AHEAD: 140,

  // Combat - RIDICULOUSLY OVERPOWERED
  PUNCH_DAMAGE: 25,
  PUNCH_RANGE: 60,
  PUNCH_KNOCKBACK: 700,
  PUNCH_LAUNCH: -250,
  PUNCH_DURATION: 180,

  KICK_DAMAGE: 40,
  KICK_RANGE: 70,
  KICK_KNOCKBACK: 900,
  KICK_LAUNCH: -400,
  KICK_DURATION: 250,

  WEB_SHOT_DAMAGE: 15,
  WEB_SHOT_RANGE: 400,
  WEB_SHOT_STUN: 2000,

  DIVE_KICK_DAMAGE: 60,
  DIVE_KICK_SPEED: 700,
  DIVE_KICK_KNOCKBACK: 1000,
  DIVE_KICK_LAUNCH: -500,

  SWING_KICK_BASE_DAMAGE: 50,
  SWING_KICK_KNOCKBACK: 1200,
  SWING_KICK_LAUNCH: -450,

  // Combo
  COMBO_TIMEOUT: 3000,
  COMBO_DAMAGE_BONUS: 0.2,

  // Hitstop - exaggerated for OP feel
  HITSTOP_LIGHT: 60,
  HITSTOP_MEDIUM: 120,
  HITSTOP_HEAVY: 180,

  // Slowmo
  SLOWMO_COMBO: 0.4,
  SLOWMO_LAST_KILL: 0.2,
  SLOWMO_DIVE_KICK: 0.3,
  SLOWMO_DURATION: 600,

  // Player health - tanky spider
  PLAYER_HP: 250,
  PLAYER_MAX_HP: 250,

  // Scoring
  SCORE_PER_HIT: 10,
  SCORE_SWING_SMASH: 50,
  SCORE_AIR_COMBO: 30,
  SCORE_WEB_FINISHER: 25,
};

export const PLAYER_CHARACTERS = {
  PETER: {
    name: 'PETER',
    bodyColor: 0x3366FF,
    accentColor: 0xEE2222,
    style: 'webPattern',
  },
  MILES: {
    name: 'MILES',
    bodyColor: 0x111111,
    accentColor: 0xFF2244,
    electricColor: 0xFFEE00,
    style: 'electric',
  },
};

export const PLAYER_STATES = {
  IDLE: 'IDLE',
  RUN: 'RUN',
  JUMP: 'JUMP',
  FALL: 'FALL',
  SWING: 'SWING',
  PUNCH: 'PUNCH',
  KICK: 'KICK',
  WEB_SHOT: 'WEB_SHOT',
  DIVE_KICK: 'DIVE_KICK',
  SWING_KICK: 'SWING_KICK',
  HIT: 'HIT',
  LAND: 'LAND',
};

export const ENEMY_STATES = {
  IDLE: 'IDLE',
  WALK: 'WALK',
  ATTACK: 'ATTACK',
  HIT: 'HIT',
  STUNNED: 'STUNNED',
  DEAD: 'DEAD',
  CHARGE: 'CHARGE',
  GROUND_POUND: 'GROUND_POUND',
  THROW: 'THROW',
  DODGE: 'DODGE',
  FLEE: 'FLEE',
  GRAB: 'GRAB',
  LEAP: 'LEAP',
  TAIL_SWEEP: 'TAIL_SWEEP',
  FLYING: 'FLYING',
  SWOOP: 'SWOOP',
  TENDRIL: 'TENDRIL',
};
