export const GAME_CONFIG = {
  // Display
  WIDTH: 1280,
  HEIGHT: 720,

  // Level
  LEVEL_WIDTH: 8000,
  GROUND_Y: 620,
  CEILING_Y: 40,

  // Player physics
  PLAYER_SPEED: 300,
  JUMP_VELOCITY: -550,
  GRAVITY: 1200,
  AIR_CONTROL: 0.7,

  // Player dimensions
  BODY_WIDTH: 30,
  BODY_HEIGHT: 60,
  HEAD_RADIUS: 10,
  LINE_WIDTH: 3,

  // Web-slinging
  WEB_MAX_LENGTH: 300,
  WEB_MIN_LENGTH: 80,
  WEB_COOLDOWN: 150,
  WEB_RELEASE_BOOST: 1.3,
  WEB_PUMP_FORCE: 600,
  WEB_ATTACH_AHEAD: 120,

  // Combat
  PUNCH_DAMAGE: 10,
  PUNCH_RANGE: 45,
  PUNCH_KNOCKBACK: 200,
  PUNCH_DURATION: 250,

  KICK_DAMAGE: 16,
  KICK_RANGE: 55,
  KICK_KNOCKBACK: 300,
  KICK_DURATION: 350,

  WEB_SHOT_DAMAGE: 5,
  WEB_SHOT_RANGE: 300,
  WEB_SHOT_STUN: 1000,

  DIVE_KICK_DAMAGE: 25,
  DIVE_KICK_SPEED: 600,
  DIVE_KICK_KNOCKBACK: 400,

  SWING_KICK_BASE_DAMAGE: 20,
  SWING_KICK_KNOCKBACK: 500,

  // Combo
  COMBO_TIMEOUT: 2000,
  COMBO_DAMAGE_BONUS: 0.1,

  // Hitstop
  HITSTOP_LIGHT: 40,
  HITSTOP_MEDIUM: 80,
  HITSTOP_HEAVY: 120,

  // Slowmo
  SLOWMO_COMBO: 0.4,
  SLOWMO_LAST_KILL: 0.2,
  SLOWMO_DIVE_KICK: 0.3,
  SLOWMO_DURATION: 600,

  // Player health
  PLAYER_HP: 100,
  PLAYER_MAX_HP: 100,

  // Scoring
  SCORE_PER_HIT: 10,
  SCORE_SWING_SMASH: 50,
  SCORE_AIR_COMBO: 30,
  SCORE_WEB_FINISHER: 25,
};

export const PLAYER_STATES = {
  IDLE: 'IDLE',
  RUN: 'RUN',
  JUMP: 'JUMP',
  FALL: 'FALL',
  SWING: 'SWING',
  PUNCH: 'PUNCH',
  KICK: 'KICK',
  WEB_SHOT: 'WEB_SHOT',
  DIVE_KICK: 'DIVE_KICK',
  SWING_KICK: 'SWING_KICK',
  HIT: 'HIT',
  LAND: 'LAND',
};

export const ENEMY_STATES = {
  IDLE: 'IDLE',
  WALK: 'WALK',
  ATTACK: 'ATTACK',
  HIT: 'HIT',
  STUNNED: 'STUNNED',
  DEAD: 'DEAD',
  CHARGE: 'CHARGE',
  GROUND_POUND: 'GROUND_POUND',
  THROW: 'THROW',
  DODGE: 'DODGE',
  FLEE: 'FLEE',
};
